### PR TITLE
Add to bloomlibrary_org.download_book as well.

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BookInstanceIdBackfiller.ts, line 417 at r2](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2#-ME9YvcZEXxAqv8hhcDU:-ME9YvcZEXxAqv8hhcDV:b-q3wg9y) ([raw file](https://github.com/bloombooks/bloom-analytics-cleanup/blob/9ab0ebcd15eb6a05b6e57b49c59c368ade22b79d/src/BookInstanceIdBackfiller.ts#L417)):*
> ```
> DISTINCT
> ```
This got lost, I think.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BookInstanceIdBackfiller.ts, line 193 at r1](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2#-ME9CsETDtNPwCzzTx9V:-ME9CsETDtNPwCzzTx9W:b-6t9uq5) ([raw file](https://github.com/bloombooks/bloom-analytics-cleanup/blob/37239d54832c3856761f2a4096f9399c056c8ad1/src/BookInstanceIdBackfiller.ts#L193)):*
> ```XML
>     }
> 
>     private getSqlLookupQuery(): string {
> ```

Note: This function used to examine 2 schemas x 3 tables = 6 total  to figure out the distinct titles.
Now, in addition to adding download_book, it should also look at questions_correct (total of 9 now).
___
*[src/BookInstanceIdBackfiller.ts, line 297 at r1](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2#-ME9Dk8p7D1w_3Brbu8J:-ME9Dk8qAAF1X6xpz1GY:b1z151f) ([raw file](https://github.com/bloombooks/bloom-analytics-cleanup/blob/37239d54832c3856761f2a4096f9399c056c8ad1/src/BookInstanceIdBackfiller.ts#L297)):*
> ```XML
>         });
> 
>         return Promise.all(updateTasks);
> ```

Not 100% sure if it's better to start off all the DB queries at once, or let the DB just worry about one thing at a time instead (using await in a for loop).
___
*[src/BookInstanceIdBackfiller.ts, line 417 at r2](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2#-ME9YvcZEXxAqv8hhcDU:-ME9adzeCKk4HAG1FqHr:b2mk55c) ([raw file](https://github.com/bloombooks/bloom-analytics-cleanup/blob/9ab0ebcd15eb6a05b6e57b49c59c368ade22b79d/src/BookInstanceIdBackfiller.ts#L417)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> DISTINCT
> ```
This got lost, I think.
</blockquote></details>

It's actually optional here since our UNION will also remove duplicates. Could go either way.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2)* status: all files reviewed, 2 unresolved discussions

___
*[src/BookInstanceIdBackfiller.ts, line 417 at r2](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2#-ME9YvcZEXxAqv8hhcDU:-ME9cQSFC4MmkeoMWwlr:b-4zq28l) ([raw file](https://github.com/bloombooks/bloom-analytics-cleanup/blob/9ab0ebcd15eb6a05b6e57b49c59c368ade22b79d/src/BookInstanceIdBackfiller.ts#L417)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

It's actually optional here since our UNION will also remove duplicates. Could go either way.
</blockquote></details>

Good point.
It is impossible (without benchmarking or analyzing the plan, of course) to know which would be more performant or if the optimizer would do the same thing either way.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2)* status: all files reviewed, 1 unresolved discussion

___
*[src/BookInstanceIdBackfiller.ts, line 297 at r1](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2#-ME9Dk8p7D1w_3Brbu8J:-ME9d6PO0AB72RGQZmM3:b-4sbvyz) ([raw file](https://github.com/bloombooks/bloom-analytics-cleanup/blob/37239d54832c3856761f2a4096f9399c056c8ad1/src/BookInstanceIdBackfiller.ts#L297)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Not 100% sure if it's better to start off all the DB queries at once, or let the DB just worry about one thing at a time instead (using await in a for loop).
</blockquote></details>

I would tend toward simpler unless we have good reason to believe it would be more performant the other way.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-analytics-cleanup/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
